### ISSUE TITLE
Put a checkmark next to completed TOC items in the viewer to make it clearer for the student. 

### ISSUE THREAD

**Issue by johnmayer** [CCALI/CALI-Author-Viewer-5#138]
Right now, the items in the TOC turn a different color when they are completed by the student. It's hard to see this. Put an icon-like checkmark in front of an item in the TOC when it is completed.

**Comment by sgoshorn** [comment]
What does "completed" mean?

**Comment by emasters** [comment]
@sgoshorn I believe what @johnmayer is getting at here is that it needs to be more obvious that a student has looked at the content under a particular entry in the ToC. We've had this discussion recently about improving the visual clues on moving through a Lesson. 
Right now as I move through a Lesson from ToC to interior pages and back, the text color of the ToC entry changes and the background of the entry gets a rather ineffective gray fade. Visually it is hard for me to track what sections I've looked at or worked through. Perhaps rather than a check mark something like reading glasses https://www.flaticon.com/free-icon/reading-glasses_304520 might be a good indicator that a student has visited a particular section.

**Comment by sgoshorn** [comment]
Where is the owl icon?

**Comment by emasters** [comment]
![ItsAnOwl20201028](https://user-images.githubusercontent.com/741239/97463165-d85e5300-1915-11eb-98c1-7d3e87be1659.PNG)
This is a screenshot, not usable, but should help in finding something that would work.

**Comment by sgoshorn** [comment]
Own icon added. 682095f19c8b4e44c91efc8c92ffd2d59612c953
